/* eslint-disable @next/next/no-img-element */
import Link from "next/link"
import Head from 'next/head'
import { sanityClient, urlFor } from "../client"

import LeftSection from "../components/LeftSection"
import Banner from "../components/Banner"
import styled from 'styled-components'



// STYLES
const Wrapper = styled.div`
display: grid;
grid-template-columns: repeat(3, 1fr);
grid-template-areas:
'a b b';

@media only screen and (max-width: 1024px) {
  margin-top: 90px;
  grid-template-columns: 1fr;
grid-template-areas:
'b'
'b'
'a';
}
`
 
 


const RightSection = styled.div`
text-align: center;
grid-area: b;
height: 100vh;
overflow-x: hidden;
background: teal;

@media only screen and (max-width: 1024px) {
  height: auto;

}
`



export const Content = styled.div`
// background: green;
display: flex;
align-items: flex-start;
flex-direction: column;
padding-left: 45px;
padding-top: 15px;

@media only screen and (max-width: 531px) {
padding-left: 15px;
}
`
 
export const PostTitle = styled.div`
text-transform: capitalize;
font-size: 25px;
display: flex;
justify-content: center;
align-items: center;
position: relative;
padding: 20px 10px;
margin-top: 100px;
color: teal;

@media only screen and (max-width: 1024px) {
 font-size: 18px;
}

@media only screen and (max-width: 834px) {
  width: 350px;
}

@media only screen and (max-width: 531px) {
  width: 300px;
}
`;
 


export const ImgWrapper = styled.div`
.img {
  width: 1200px;
  height: 700px;
  border: solid 2px black;
}
`
//END STYLES



const Home = ({ posts }) => {
  return (
    <>
          <Head>
        <title>WTBH</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="p:domain_verify" content="0eb994c4a2db7b6db7409469d390cc92"/>
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <Wrapper>
       <LeftSection />
            


  <RightSection>
              <Banner />
                          {posts &&
                          posts.map((post, index) => (   
                            <span key={index}>
                                     <Link href={`post/${post.slug.current}`}>
                             <Content>
                             <PostTitle>{post.title}</PostTitle>
                             <ImgWrapper>
                                  <img
                                  src={urlFor(post.mainImage)}
                                  alt="main pic"
                                    layout="responsive"
                                  className="img"
                                  />
                                  </ImgWrapper>
                            </Content>
                                
                                     
                            </Link>
                              </span>   
                            ))}
       </RightSection>
    </Wrapper>
    </>
  )
}



export const getServerSideProps = async() => {
  const query = '*[_type == "blogPosts"]'
  const posts = await sanityClient.fetch(query)
  if (!posts.length) {
    return {
      props: {
        posts: [],
      },
    }
  } else {
    return {
      props: {
        posts,
      },
    }
  }
}
 

export default Home